// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int select(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timeval> __timeout,
  ) {
    return _select(
      __nfds,
      __readfds,
      __writefds,
      __exceptfds,
      __timeout,
    );
  }

  late final _selectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<fd_set>, ffi.Pointer<fd_set>,
              ffi.Pointer<fd_set>, ffi.Pointer<timeval>)>>('select');
  late final _select = _selectPtr.asFunction<
      int Function(int, ffi.Pointer<fd_set>, ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>, ffi.Pointer<timeval>)>();

  int pselect(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timespec> __timeout,
    ffi.Pointer<__sigset_t> __sigmask,
  ) {
    return _pselect(
      __nfds,
      __readfds,
      __writefds,
      __exceptfds,
      __timeout,
      __sigmask,
    );
  }

  late final _pselectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int,
              ffi.Pointer<fd_set>,
              ffi.Pointer<fd_set>,
              ffi.Pointer<fd_set>,
              ffi.Pointer<timespec>,
              ffi.Pointer<__sigset_t>)>>('pselect');
  late final _pselect = _pselectPtr.asFunction<
      int Function(
          int,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<timespec>,
          ffi.Pointer<__sigset_t>)>();

  int imaxabs(
    int __n,
  ) {
    return _imaxabs(
      __n,
    );
  }

  late final _imaxabsPtr =
      _lookup<ffi.NativeFunction<intmax_t Function(intmax_t)>>('imaxabs');
  late final _imaxabs = _imaxabsPtr.asFunction<int Function(int)>();

  imaxdiv_t imaxdiv(
    int __numer,
    int __denom,
  ) {
    return _imaxdiv(
      __numer,
      __denom,
    );
  }

  late final _imaxdivPtr =
      _lookup<ffi.NativeFunction<imaxdiv_t Function(intmax_t, intmax_t)>>(
          'imaxdiv');
  late final _imaxdiv = _imaxdivPtr.asFunction<imaxdiv_t Function(int, int)>();

  int strtoimax(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoimax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoimaxPtr = _lookup<
      ffi.NativeFunction<
          intmax_t Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>>('strtoimax');
  late final _strtoimax = _strtoimaxPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  int strtoumax(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoumax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoumaxPtr = _lookup<
      ffi.NativeFunction<
          uintmax_t Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>>('strtoumax');
  late final _strtoumax = _strtoumaxPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  int wcstoimax(
    ffi.Pointer<__gwchar_t> __nptr,
    ffi.Pointer<ffi.Pointer<__gwchar_t>> __endptr,
    int __base,
  ) {
    return _wcstoimax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _wcstoimaxPtr = _lookup<
      ffi.NativeFunction<
          intmax_t Function(ffi.Pointer<__gwchar_t>,
              ffi.Pointer<ffi.Pointer<__gwchar_t>>, ffi.Int)>>('wcstoimax');
  late final _wcstoimax = _wcstoimaxPtr.asFunction<
      int Function(ffi.Pointer<__gwchar_t>,
          ffi.Pointer<ffi.Pointer<__gwchar_t>>, int)>();

  int wcstoumax(
    ffi.Pointer<__gwchar_t> __nptr,
    ffi.Pointer<ffi.Pointer<__gwchar_t>> __endptr,
    int __base,
  ) {
    return _wcstoumax(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _wcstoumaxPtr = _lookup<
      ffi.NativeFunction<
          uintmax_t Function(ffi.Pointer<__gwchar_t>,
              ffi.Pointer<ffi.Pointer<__gwchar_t>>, ffi.Int)>>('wcstoumax');
  late final _wcstoumax = _wcstoumaxPtr.asFunction<
      int Function(ffi.Pointer<__gwchar_t>,
          ffi.Pointer<ffi.Pointer<__gwchar_t>>, int)>();

  int SHA1_Init(
    ffi.Pointer<SHA_CTX> c,
  ) {
    return _SHA1_Init(
      c,
    );
  }

  late final _SHA1_InitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHA_CTX>)>>(
          'SHA1_Init');
  late final _SHA1_Init =
      _SHA1_InitPtr.asFunction<int Function(ffi.Pointer<SHA_CTX>)>();

  int SHA1_Update(
    ffi.Pointer<SHA_CTX> c,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _SHA1_Update(
      c,
      data,
      len,
    );
  }

  late final _SHA1_UpdatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SHA_CTX>, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('SHA1_Update');
  late final _SHA1_Update = _SHA1_UpdatePtr.asFunction<
      int Function(ffi.Pointer<SHA_CTX>, ffi.Pointer<ffi.Void>, int)>();

  int SHA1_Final(
    ffi.Pointer<ffi.UnsignedChar> md,
    ffi.Pointer<SHA_CTX> c,
  ) {
    return _SHA1_Final(
      md,
      c,
    );
  }

  late final _SHA1_FinalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Pointer<SHA_CTX>)>>('SHA1_Final');
  late final _SHA1_Final = _SHA1_FinalPtr.asFunction<
      int Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Pointer<SHA_CTX>)>();

  void SHA1_Transform(
    ffi.Pointer<SHA_CTX> c,
    ffi.Pointer<ffi.UnsignedChar> data,
  ) {
    return _SHA1_Transform(
      c,
      data,
    );
  }

  late final _SHA1_TransformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SHA_CTX>,
              ffi.Pointer<ffi.UnsignedChar>)>>('SHA1_Transform');
  late final _SHA1_Transform = _SHA1_TransformPtr.asFunction<
      void Function(ffi.Pointer<SHA_CTX>, ffi.Pointer<ffi.UnsignedChar>)>();

  ffi.Pointer<ffi.UnsignedChar> SHA1(
    ffi.Pointer<ffi.UnsignedChar> d,
    int n,
    ffi.Pointer<ffi.UnsignedChar> md,
  ) {
    return _SHA1(
      d,
      n,
      md,
    );
  }

  late final _SHA1Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size, ffi.Pointer<ffi.UnsignedChar>)>>('SHA1');
  late final _SHA1 = _SHA1Ptr.asFunction<
      ffi.Pointer<ffi.UnsignedChar> Function(
          ffi.Pointer<ffi.UnsignedChar>, int, ffi.Pointer<ffi.UnsignedChar>)>();

  int SHA224_Init(
    ffi.Pointer<SHA256_CTX> c,
  ) {
    return _SHA224_Init(
      c,
    );
  }

  late final _SHA224_InitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHA256_CTX>)>>(
          'SHA224_Init');
  late final _SHA224_Init =
      _SHA224_InitPtr.asFunction<int Function(ffi.Pointer<SHA256_CTX>)>();

  int SHA224_Update(
    ffi.Pointer<SHA256_CTX> c,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _SHA224_Update(
      c,
      data,
      len,
    );
  }

  late final _SHA224_UpdatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SHA256_CTX>, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('SHA224_Update');
  late final _SHA224_Update = _SHA224_UpdatePtr.asFunction<
      int Function(ffi.Pointer<SHA256_CTX>, ffi.Pointer<ffi.Void>, int)>();

  int SHA224_Final(
    ffi.Pointer<ffi.UnsignedChar> md,
    ffi.Pointer<SHA256_CTX> c,
  ) {
    return _SHA224_Final(
      md,
      c,
    );
  }

  late final _SHA224_FinalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Pointer<SHA256_CTX>)>>('SHA224_Final');
  late final _SHA224_Final = _SHA224_FinalPtr.asFunction<
      int Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Pointer<SHA256_CTX>)>();

  int SHA256_Init(
    ffi.Pointer<SHA256_CTX> c,
  ) {
    return _SHA256_Init(
      c,
    );
  }

  late final _SHA256_InitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHA256_CTX>)>>(
          'SHA256_Init');
  late final _SHA256_Init =
      _SHA256_InitPtr.asFunction<int Function(ffi.Pointer<SHA256_CTX>)>();

  int SHA256_Update(
    ffi.Pointer<SHA256_CTX> c,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _SHA256_Update(
      c,
      data,
      len,
    );
  }

  late final _SHA256_UpdatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SHA256_CTX>, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('SHA256_Update');
  late final _SHA256_Update = _SHA256_UpdatePtr.asFunction<
      int Function(ffi.Pointer<SHA256_CTX>, ffi.Pointer<ffi.Void>, int)>();

  int SHA256_Final(
    ffi.Pointer<ffi.UnsignedChar> md,
    ffi.Pointer<SHA256_CTX> c,
  ) {
    return _SHA256_Final(
      md,
      c,
    );
  }

  late final _SHA256_FinalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Pointer<SHA256_CTX>)>>('SHA256_Final');
  late final _SHA256_Final = _SHA256_FinalPtr.asFunction<
      int Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Pointer<SHA256_CTX>)>();

  void SHA256_Transform(
    ffi.Pointer<SHA256_CTX> c,
    ffi.Pointer<ffi.UnsignedChar> data,
  ) {
    return _SHA256_Transform(
      c,
      data,
    );
  }

  late final _SHA256_TransformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SHA256_CTX>,
              ffi.Pointer<ffi.UnsignedChar>)>>('SHA256_Transform');
  late final _SHA256_Transform = _SHA256_TransformPtr.asFunction<
      void Function(ffi.Pointer<SHA256_CTX>, ffi.Pointer<ffi.UnsignedChar>)>();

  ffi.Pointer<ffi.UnsignedChar> SHA224(
    ffi.Pointer<ffi.UnsignedChar> d,
    int n,
    ffi.Pointer<ffi.UnsignedChar> md,
  ) {
    return _SHA224(
      d,
      n,
      md,
    );
  }

  late final _SHA224Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size, ffi.Pointer<ffi.UnsignedChar>)>>('SHA224');
  late final _SHA224 = _SHA224Ptr.asFunction<
      ffi.Pointer<ffi.UnsignedChar> Function(
          ffi.Pointer<ffi.UnsignedChar>, int, ffi.Pointer<ffi.UnsignedChar>)>();

  ffi.Pointer<ffi.UnsignedChar> SHA256(
    ffi.Pointer<ffi.UnsignedChar> d,
    int n,
    ffi.Pointer<ffi.UnsignedChar> md,
  ) {
    return _SHA256(
      d,
      n,
      md,
    );
  }

  late final _SHA256Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size, ffi.Pointer<ffi.UnsignedChar>)>>('SHA256');
  late final _SHA256 = _SHA256Ptr.asFunction<
      ffi.Pointer<ffi.UnsignedChar> Function(
          ffi.Pointer<ffi.UnsignedChar>, int, ffi.Pointer<ffi.UnsignedChar>)>();

  int SHA384_Init(
    ffi.Pointer<SHA512_CTX> c,
  ) {
    return _SHA384_Init(
      c,
    );
  }

  late final _SHA384_InitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHA512_CTX>)>>(
          'SHA384_Init');
  late final _SHA384_Init =
      _SHA384_InitPtr.asFunction<int Function(ffi.Pointer<SHA512_CTX>)>();

  int SHA384_Update(
    ffi.Pointer<SHA512_CTX> c,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _SHA384_Update(
      c,
      data,
      len,
    );
  }

  late final _SHA384_UpdatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SHA512_CTX>, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('SHA384_Update');
  late final _SHA384_Update = _SHA384_UpdatePtr.asFunction<
      int Function(ffi.Pointer<SHA512_CTX>, ffi.Pointer<ffi.Void>, int)>();

  int SHA384_Final(
    ffi.Pointer<ffi.UnsignedChar> md,
    ffi.Pointer<SHA512_CTX> c,
  ) {
    return _SHA384_Final(
      md,
      c,
    );
  }

  late final _SHA384_FinalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Pointer<SHA512_CTX>)>>('SHA384_Final');
  late final _SHA384_Final = _SHA384_FinalPtr.asFunction<
      int Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Pointer<SHA512_CTX>)>();

  int SHA512_Init(
    ffi.Pointer<SHA512_CTX> c,
  ) {
    return _SHA512_Init(
      c,
    );
  }

  late final _SHA512_InitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHA512_CTX>)>>(
          'SHA512_Init');
  late final _SHA512_Init =
      _SHA512_InitPtr.asFunction<int Function(ffi.Pointer<SHA512_CTX>)>();

  int SHA512_Update(
    ffi.Pointer<SHA512_CTX> c,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _SHA512_Update(
      c,
      data,
      len,
    );
  }

  late final _SHA512_UpdatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SHA512_CTX>, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('SHA512_Update');
  late final _SHA512_Update = _SHA512_UpdatePtr.asFunction<
      int Function(ffi.Pointer<SHA512_CTX>, ffi.Pointer<ffi.Void>, int)>();

  int SHA512_Final(
    ffi.Pointer<ffi.UnsignedChar> md,
    ffi.Pointer<SHA512_CTX> c,
  ) {
    return _SHA512_Final(
      md,
      c,
    );
  }

  late final _SHA512_FinalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Pointer<SHA512_CTX>)>>('SHA512_Final');
  late final _SHA512_Final = _SHA512_FinalPtr.asFunction<
      int Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Pointer<SHA512_CTX>)>();

  void SHA512_Transform(
    ffi.Pointer<SHA512_CTX> c,
    ffi.Pointer<ffi.UnsignedChar> data,
  ) {
    return _SHA512_Transform(
      c,
      data,
    );
  }

  late final _SHA512_TransformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SHA512_CTX>,
              ffi.Pointer<ffi.UnsignedChar>)>>('SHA512_Transform');
  late final _SHA512_Transform = _SHA512_TransformPtr.asFunction<
      void Function(ffi.Pointer<SHA512_CTX>, ffi.Pointer<ffi.UnsignedChar>)>();

  ffi.Pointer<ffi.UnsignedChar> SHA384(
    ffi.Pointer<ffi.UnsignedChar> d,
    int n,
    ffi.Pointer<ffi.UnsignedChar> md,
  ) {
    return _SHA384(
      d,
      n,
      md,
    );
  }

  late final _SHA384Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size, ffi.Pointer<ffi.UnsignedChar>)>>('SHA384');
  late final _SHA384 = _SHA384Ptr.asFunction<
      ffi.Pointer<ffi.UnsignedChar> Function(
          ffi.Pointer<ffi.UnsignedChar>, int, ffi.Pointer<ffi.UnsignedChar>)>();

  ffi.Pointer<ffi.UnsignedChar> SHA512(
    ffi.Pointer<ffi.UnsignedChar> d,
    int n,
    ffi.Pointer<ffi.UnsignedChar> md,
  ) {
    return _SHA512(
      d,
      n,
      md,
    );
  }

  late final _SHA512Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size, ffi.Pointer<ffi.UnsignedChar>)>>('SHA512');
  late final _SHA512 = _SHA512Ptr.asFunction<
      ffi.Pointer<ffi.UnsignedChar> Function(
          ffi.Pointer<ffi.UnsignedChar>, int, ffi.Pointer<ffi.UnsignedChar>)>();
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef u_char = __u_char;
typedef u_short = __u_short;
typedef u_int = __u_int;
typedef u_long = __u_long;
typedef quad_t = __quad_t;
typedef u_quad_t = __u_quad_t;
typedef fsid_t = __fsid_t;
typedef loff_t = __loff_t;
typedef ino_t = __ino_t;
typedef dev_t = __dev_t;
typedef gid_t = __gid_t;
typedef mode_t = __mode_t;
typedef nlink_t = __nlink_t;
typedef uid_t = __uid_t;
typedef off_t = __off_t;
typedef pid_t = __pid_t;
typedef id_t = __id_t;
typedef ssize_t = __ssize_t;
typedef daddr_t = __daddr_t;
typedef caddr_t = __caddr_t;
typedef key_t = __key_t;
typedef clock_t = __clock_t;
typedef clockid_t = __clockid_t;
typedef time_t = __time_t;
typedef timer_t = __timer_t;
typedef ulong = ffi.UnsignedLong;
typedef Dartulong = int;
typedef ushort = ffi.UnsignedShort;
typedef Dartushort = int;
typedef uint = ffi.UnsignedInt;
typedef Dartuint = int;
typedef u_int8_t = __uint8_t;
typedef u_int16_t = __uint16_t;
typedef u_int32_t = __uint32_t;
typedef u_int64_t = __uint64_t;
typedef register_t = ffi.Long;
typedef Dartregister_t = int;

final class __sigset_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __val;
}

typedef sigset_t = __sigset_t;

final class timeval extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__suseconds_t()
  external int tv_usec;
}

final class timespec extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__syscall_slong_t()
  external int tv_nsec;
}

typedef suseconds_t = __suseconds_t;
typedef __fd_mask = ffi.Long;
typedef Dart__fd_mask = int;

final class fd_set extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<__fd_mask> __fds_bits;
}

typedef fd_mask = __fd_mask;
typedef blksize_t = __blksize_t;
typedef blkcnt_t = __blkcnt_t;
typedef fsblkcnt_t = __fsblkcnt_t;
typedef fsfilcnt_t = __fsfilcnt_t;

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct1 __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

typedef __pthread_list_t = __pthread_internal_list;

final class __pthread_internal_slist extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_slist> __next;
}

typedef __pthread_slist_t = __pthread_internal_slist;

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_list_t __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;

  @ffi.UnsignedInt()
  external int __unused_initialized_1;

  @ffi.UnsignedInt()
  external int __unused_initialized_2;
}

typedef __tss_t = ffi.UnsignedInt;
typedef Dart__tss_t = int;
typedef __thrd_t = ffi.UnsignedLong;
typedef Dart__thrd_t = int;

final class __once_flag extends ffi.Struct {
  @ffi.Int()
  external int __data;
}

typedef pthread_t = ffi.UnsignedLong;
typedef Dartpthread_t = int;

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef pthread_key_t = ffi.UnsignedInt;
typedef Dartpthread_key_t = int;
typedef pthread_once_t = ffi.Int;
typedef Dartpthread_once_t = int;

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;
typedef __gwchar_t = ffi.Int;
typedef Dart__gwchar_t = int;

final class imaxdiv_t extends ffi.Struct {
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;
}

typedef ossl_intmax_t = intmax_t;
typedef ossl_uintmax_t = uintmax_t;
typedef ptrdiff_t = ffi.Long;
typedef Dartptrdiff_t = int;

final class max_align_t extends ffi.Opaque {}

final class SHAstate_st extends ffi.Struct {
  @ffi.UnsignedInt()
  external int h0;

  @ffi.UnsignedInt()
  external int h1;

  @ffi.UnsignedInt()
  external int h2;

  @ffi.UnsignedInt()
  external int h3;

  @ffi.UnsignedInt()
  external int h4;

  @ffi.UnsignedInt()
  external int Nl;

  @ffi.UnsignedInt()
  external int Nh;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedInt> data;

  @ffi.UnsignedInt()
  external int num;
}

typedef SHA_CTX = SHAstate_st;

final class SHA256state_st extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.UnsignedInt> h;

  @ffi.UnsignedInt()
  external int Nl;

  @ffi.UnsignedInt()
  external int Nh;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedInt> data;

  @ffi.UnsignedInt()
  external int num;

  @ffi.UnsignedInt()
  external int md_len;
}

typedef SHA256_CTX = SHA256state_st;

final class UnnamedUnion1 extends ffi.Union {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLongLong> d;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.UnsignedChar> p;
}

final class SHA512state_st extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.UnsignedLongLong> h;

  @ffi.UnsignedLongLong()
  external int Nl;

  @ffi.UnsignedLongLong()
  external int Nh;

  external UnnamedUnion1 u;

  @ffi.UnsignedInt()
  external int num;

  @ffi.UnsignedInt()
  external int md_len;
}

typedef SHA512_CTX = SHA512state_st;

const int OPENSSL_CONFIGURED_API = 30400;

const int OPENSSL_VERSION_MAJOR = 3;

const int OPENSSL_VERSION_MINOR = 4;

const int OPENSSL_VERSION_PATCH = 1;

const String OPENSSL_VERSION_PRE_RELEASE = '';

const String OPENSSL_VERSION_BUILD_METADATA = '';

const int OPENSSL_SHLIB_VERSION = 3;

const String OPENSSL_VERSION_STR = '3.4.1';

const String OPENSSL_FULL_VERSION_STR = '3.4.1';

const String OPENSSL_RELEASE_DATE = '11 Feb 2025';

const String OPENSSL_VERSION_TEXT = 'OpenSSL 3.4.1 11 Feb 2025';

const int _OPENSSL_VERSION_PRE_RELEASE = 0;

const int OPENSSL_VERSION_NUMBER = 809500688;

const int OPENSSL_API_LEVEL = 30400;

const String OPENSSL_FILE = '/tmp/CRZCLZ/temp_for_macros.hpp';

const int OPENSSL_LINE = 70;

const String OPENSSL_FUNC = '(unknown function)';

const int _SYS_TYPES_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2Y = 1;

const int __GLIBC_USE_ISOC23 = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_TIME_BITS64 = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C23_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 41;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int __clock_t_defined = 1;

const int __clockid_t_defined = 1;

const int __time_t_defined = 1;

const int __timer_t_defined = 1;

const int _BITS_STDINT_INTN_H = 1;

const int __BIT_TYPES_DEFINED__ = 1;

const int _ENDIAN_H = 1;

const int _BITS_ENDIAN_H = 1;

const int __LITTLE_ENDIAN = 1234;

const int __BIG_ENDIAN = 4321;

const int __PDP_ENDIAN = 3412;

const int _BITS_ENDIANNESS_H = 1;

const int __BYTE_ORDER = 1234;

const int __FLOAT_WORD_ORDER = 1234;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int _BITS_BYTESWAP_H = 1;

const int _BITS_UINTN_IDENTITY_H = 1;

const int _SYS_SELECT_H = 1;

const int __sigset_t_defined = 1;

const int _SIGSET_NWORDS = 16;

const int __timeval_defined = 1;

const int _STRUCT_TIMESPEC = 1;

const int __NFDBITS = 64;

const int FD_SETSIZE = 1024;

const int NFDBITS = 64;

const int _BITS_PTHREADTYPES_COMMON_H = 1;

const int _THREAD_SHARED_TYPES_H = 1;

const int _BITS_PTHREADTYPES_ARCH_H = 1;

const int __SIZEOF_PTHREAD_MUTEX_T = 40;

const int __SIZEOF_PTHREAD_ATTR_T = 56;

const int __SIZEOF_PTHREAD_RWLOCK_T = 56;

const int __SIZEOF_PTHREAD_BARRIER_T = 32;

const int __SIZEOF_PTHREAD_MUTEXATTR_T = 4;

const int __SIZEOF_PTHREAD_COND_T = 48;

const int __SIZEOF_PTHREAD_CONDATTR_T = 4;

const int __SIZEOF_PTHREAD_RWLOCKATTR_T = 8;

const int __SIZEOF_PTHREAD_BARRIERATTR_T = 4;

const int _THREAD_MUTEX_INTERNAL_H = 1;

const int __PTHREAD_MUTEX_HAVE_PREV = 1;

const int __PTHREAD_RWLOCK_ELISION_EXTRA = 0;

const int __have_pthread_attr_t = 1;

const int OSSL_SSIZE_MAX = 9223372036854775807;

const int _STDINT_H = 1;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;

const int NULL = 0;

const int SHA_DIGEST_LENGTH = 20;

const int SHA_LBLOCK = 16;

const int SHA_CBLOCK = 64;

const int SHA_LAST_BLOCK = 56;

const int SHA256_CBLOCK = 64;

const int SHA256_192_DIGEST_LENGTH = 24;

const int SHA224_DIGEST_LENGTH = 28;

const int SHA256_DIGEST_LENGTH = 32;

const int SHA384_DIGEST_LENGTH = 48;

const int SHA512_DIGEST_LENGTH = 64;

const int SHA512_CBLOCK = 128;
